language: go
env:
  global:
    secure: "CWfPtMm4vMSiEPmiQ3zfkQ"
    
jobs:
    include:
        - stage: Fuzz regression
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - chmod +x fuzzit.sh 
              - ./fuzzit.sh local-regression
        - stage: Fuzz
          if: branch = master AND type IN (push)
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              -  chmod +x fuzzit.sh 
              - sh fuzzit.sh fuzzing

env:
    GO15VENDOREXPERIMENT=1
