language: go

env:
  global:
      secure: "339773068c2d0656b6dfbd3894aca9dd67cd7077a1974def6123fb4d62114d00313ffb79c42302c804e6793e92fdb6d4f"
jobs:
    include:
        - stage: Fuzz regression
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - chmod +x fuzzit.sh 
              - ./fuzzit.sh local-regression
        - stage: Fuzz
          if: branch = master AND type IN (push)
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - chmod +x fuzzit.sh 
              - ./fuzzit.sh fuzzing
