language: go
go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
script: go test -v ./.

jobs:
    include:
        - stage: Fuzz regression
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - sh fuzzit.sh local-regression
        - stage: Fuzz
          if: branch = master AND type IN (push)
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - sh fuzzit.sh fuzzing

env:
    GO15VENDOREXPERIMENT=1
