language: go

env:
  global:
    # This is FUZZIT_API_KEY. see https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables for how to create secrets in Travis.
    secure: $FUZZIT_API_KEY 
    
jobs:
    include:
        - stage: Fuzz regression
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - chmod +x fuzzit.sh 
              - ./fuzzit.sh local-regression
        - stage: Fuzz
          #if: branch = master AND type IN (push)
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - chmod +x fuzzit.sh 
              - ./fuzzit.sh fuzzing
