language: go

jobs:
    include:
        - stage: Fuzz regression
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - sh fuzzit.sh local-regression
        - stage: Fuzz
          if: branch = master AND type IN (push)
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - sh fuzzit.sh fuzzing

env:
    GO15VENDOREXPERIMENT=1
