language: go
script:
    - travis encrypt SOMEVAR="secretvalue"  --add
    
jobs:
    include:
        - stage: Fuzz regression
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              - chmod +x fuzzit.sh 
              - ./fuzzit.sh local-regression
        - stage: Fuzz
          if: branch = master AND type IN (push)
          go: 1.12.x
          dist: bionic
          script:
              - cd fuzztest
              -  chmod +x fuzzit.sh 
              - sh fuzzit.sh fuzzing

env:
    GO15VENDOREXPERIMENT=1
